# Config file for automatic testing at travis-ci.org

sudo: required
language: python
dist: xenial
matrix:
    include:
      - python: 3.6
        env: TOX_ENV=py36
      - python: 3.7
        env: TOX_ENV=py37

install:
  - pip install tox
  - make tests/test_capture.py

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
